/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedNewSessionRouteImport } from './routes/_authenticated/new-session'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as ApiAnswerStreamRouteImport } from './routes/api/answer-stream'
import { Route as AuthenticatedAdminDesktopReleasesRouteImport } from './routes/_authenticated/admin/desktop-releases'
import { Route as AuthenticatedHistoryIndexRouteImport } from './routes/_authenticated/history.index'
import { Route as AuthenticatedHistorySessionIdRouteImport } from './routes/_authenticated/history.$sessionId'
import { Route as AuthenticatedSessionSessionIdRouteImport } from './routes/_authenticated/session.$sessionId'
import { Route as ApiPublicDesktopReleaseRouteImport } from './routes/api/public/desktop-release'
import { Route as ApiPublicCompanionPairRouteImport } from './routes/api/public/companion/pair'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewSessionRoute = AuthenticatedNewSessionRouteImport.update({
  id: '/new-session',
  path: '/new-session',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAnswerStreamRoute = ApiAnswerStreamRouteImport.update({
  id: '/api/answer-stream',
  path: '/api/answer-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminDesktopReleasesRoute =
  AuthenticatedAdminDesktopReleasesRouteImport.update({
    id: '/admin/desktop-releases',
    path: '/admin/desktop-releases',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoryIndexRoute =
  AuthenticatedHistoryIndexRouteImport.update({
    id: '/history/',
    path: '/history/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistorySessionIdRoute =
  AuthenticatedHistorySessionIdRouteImport.update({
    id: '/history/$sessionId',
    path: '/history/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionSessionIdRoute =
  AuthenticatedSessionSessionIdRouteImport.update({
    id: '/session/$sessionId',
    path: '/session/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicDesktopReleaseRoute = ApiPublicDesktopReleaseRouteImport.update({
  id: '/api/public/desktop-release',
  path: '/api/public/desktop-release',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCompanionPairRoute = ApiPublicCompanionPairRouteImport.update({
  id: '/api/public/companion/pair',
  path: '/api/public/companion/pair',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/new-session': typeof AuthenticatedNewSessionRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/answer-stream': typeof ApiAnswerStreamRoute
  '/admin/desktop-releases': typeof AuthenticatedAdminDesktopReleasesRoute
  '/history/$sessionId': typeof AuthenticatedHistorySessionIdRoute
  '/session/$sessionId': typeof AuthenticatedSessionSessionIdRoute
  '/api/public/desktop-release': typeof ApiPublicDesktopReleaseRoute
  '/history/': typeof AuthenticatedHistoryIndexRoute
  '/api/public/companion/pair': typeof ApiPublicCompanionPairRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/new-session': typeof AuthenticatedNewSessionRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/answer-stream': typeof ApiAnswerStreamRoute
  '/admin/desktop-releases': typeof AuthenticatedAdminDesktopReleasesRoute
  '/history/$sessionId': typeof AuthenticatedHistorySessionIdRoute
  '/session/$sessionId': typeof AuthenticatedSessionSessionIdRoute
  '/api/public/desktop-release': typeof ApiPublicDesktopReleaseRoute
  '/history': typeof AuthenticatedHistoryIndexRoute
  '/api/public/companion/pair': typeof ApiPublicCompanionPairRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/new-session': typeof AuthenticatedNewSessionRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/answer-stream': typeof ApiAnswerStreamRoute
  '/_authenticated/admin/desktop-releases': typeof AuthenticatedAdminDesktopReleasesRoute
  '/_authenticated/history/$sessionId': typeof AuthenticatedHistorySessionIdRoute
  '/_authenticated/session/$sessionId': typeof AuthenticatedSessionSessionIdRoute
  '/api/public/desktop-release': typeof ApiPublicDesktopReleaseRoute
  '/_authenticated/history/': typeof AuthenticatedHistoryIndexRoute
  '/api/public/companion/pair': typeof ApiPublicCompanionPairRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/download'
    | '/dashboard'
    | '/documents'
    | '/new-session'
    | '/settings'
    | '/api/answer-stream'
    | '/admin/desktop-releases'
    | '/history/$sessionId'
    | '/session/$sessionId'
    | '/api/public/desktop-release'
    | '/history/'
    | '/api/public/companion/pair'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/download'
    | '/dashboard'
    | '/documents'
    | '/new-session'
    | '/settings'
    | '/api/answer-stream'
    | '/admin/desktop-releases'
    | '/history/$sessionId'
    | '/session/$sessionId'
    | '/api/public/desktop-release'
    | '/history'
    | '/api/public/companion/pair'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/download'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/new-session'
    | '/_authenticated/settings'
    | '/api/answer-stream'
    | '/_authenticated/admin/desktop-releases'
    | '/_authenticated/history/$sessionId'
    | '/_authenticated/session/$sessionId'
    | '/api/public/desktop-release'
    | '/_authenticated/history/'
    | '/api/public/companion/pair'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DownloadRoute: typeof DownloadRoute
  ApiAnswerStreamRoute: typeof ApiAnswerStreamRoute
  ApiPublicDesktopReleaseRoute: typeof ApiPublicDesktopReleaseRoute
  ApiPublicCompanionPairRoute: typeof ApiPublicCompanionPairRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-session': {
      id: '/_authenticated/new-session'
      path: '/new-session'
      fullPath: '/new-session'
      preLoaderRoute: typeof AuthenticatedNewSessionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/answer-stream': {
      id: '/api/answer-stream'
      path: '/api/answer-stream'
      fullPath: '/api/answer-stream'
      preLoaderRoute: typeof ApiAnswerStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/desktop-releases': {
      id: '/_authenticated/admin/desktop-releases'
      path: '/admin/desktop-releases'
      fullPath: '/admin/desktop-releases'
      preLoaderRoute: typeof AuthenticatedAdminDesktopReleasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history/': {
      id: '/_authenticated/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof AuthenticatedHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history/$sessionId': {
      id: '/_authenticated/history/$sessionId'
      path: '/history/$sessionId'
      fullPath: '/history/$sessionId'
      preLoaderRoute: typeof AuthenticatedHistorySessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/session/$sessionId': {
      id: '/_authenticated/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof AuthenticatedSessionSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/desktop-release': {
      id: '/api/public/desktop-release'
      path: '/api/public/desktop-release'
      fullPath: '/api/public/desktop-release'
      preLoaderRoute: typeof ApiPublicDesktopReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/companion/pair': {
      id: '/api/public/companion/pair'
      path: '/api/public/companion/pair'
      fullPath: '/api/public/companion/pair'
      preLoaderRoute: typeof ApiPublicCompanionPairRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedNewSessionRoute: typeof AuthenticatedNewSessionRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAdminDesktopReleasesRoute: typeof AuthenticatedAdminDesktopReleasesRoute
  AuthenticatedHistorySessionIdRoute: typeof AuthenticatedHistorySessionIdRoute
  AuthenticatedSessionSessionIdRoute: typeof AuthenticatedSessionSessionIdRoute
  AuthenticatedHistoryIndexRoute: typeof AuthenticatedHistoryIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedNewSessionRoute: AuthenticatedNewSessionRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAdminDesktopReleasesRoute:
    AuthenticatedAdminDesktopReleasesRoute,
  AuthenticatedHistorySessionIdRoute: AuthenticatedHistorySessionIdRoute,
  AuthenticatedSessionSessionIdRoute: AuthenticatedSessionSessionIdRoute,
  AuthenticatedHistoryIndexRoute: AuthenticatedHistoryIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DownloadRoute: DownloadRoute,
  ApiAnswerStreamRoute: ApiAnswerStreamRoute,
  ApiPublicDesktopReleaseRoute: ApiPublicDesktopReleaseRoute,
  ApiPublicCompanionPairRoute: ApiPublicCompanionPairRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
